#Engine Configuration (saved from ImGui)
#Tue Sep 15 16:59:23 KST 2026
camera.distance=4.16
camera.editPitchLimitDeg=85.0
camera.editorLookSensitivity=0.005
camera.editorSpeed=0.2
camera.editorSpeedMultiplier=2.5
camera.editorZoomSpeed=0.6
camera.orthoLerp=0.12
camera.pitch=0.2
camera.playLookSensitivity=0.0025
camera.playPitchMaxDeg=85.0
camera.playPitchMinDeg=-10.0
camera.smoothLerp=0.15
camera.smoothPosX=0.0
camera.smoothPosY=0.8
camera.smoothPosZ=0.0
camera.targetYOffset=0.3
camera.yaw=0.0
editor.dragSensitivity=0.02
editor.focusMinDistance=3.0
editor.focusSizeFactor=2.0
editor.initOffsetX=3.0
editor.initOffsetY=3.0
editor.initOffsetZ=3.0
editor.initPitchDeg=30.0
editor.initYaw=-0.75
editor.orbitDistFallback=5.0
editor.orbitDistMax=50.0
editor.orbitDistMin=0.5
editor.orbitPitchLimit=1.5
editor.orbitRotSpeed=0.005
editor.orbitZoomFactor=0.15
editor.rotDragSpeed=0.015
editor.scaleMin=0.1
engine.dtClamp=0.05
engine.glslVersion=\#version 120
game.initialBlocks=3.0,0.0,0.0,1.0,1.0,1.0 ; 0.0,3.0,0.0,1.0,1.0,1.0 ; 0.0,0.0,3.0,1.0,1.0,1.0
game.jumpScaleXZ=0.7
game.jumpScaleY=1.4
game.landScaleXZ=1.3
game.landScaleY=0.6
game.moveSpeed=0.08
game.playerPosX=0.0
game.playerPosY=0.5
game.playerPosZ=0.0
game.playerSize=1.0
game.scaleLerp=0.15
gizmo.axisLength=2.0
gizmo.axisThickness=0.3
gizmo.handleCubeSize=0.3
gizmo.pickEpsilon=1.0E-6
gizmo.ringRadius=2.0
gizmo.ringSegments=32
gizmo.ringThickness=0.3
light.ambient=0.101
light.diffuse=1.323
light.posX=8.63
light.posY=7.808
light.posZ=6.0
physics.gravity=-0.015
physics.jumpStrength=0.32
physics.scaleInit=1.0
physics.velocityY=0.0
render.camFar=100.0
render.camFovDeg=60.0
render.camNear=0.1
render.clearColor=0.53, 0.81, 0.92, 1.0
render.colorBlock=0.95, 0.5, 0.2
render.colorGrid=0.0, 0.0, 0.0
render.colorGround=0.6764706, 0.92387545, 1.0
render.colorHighlight=1.0, 1.0, 0.0
render.colorPlayerAir=0.1, 0.6, 1.0
render.colorPlayerGround=0.2, 0.9, 1.0
render.cubeHalf=0.5
render.gridHalfCount=8
render.gridLineY=0.001
render.groundHalf=11.829
render.highlightScale=1.02
render.lightFar=123.852
render.lightNear=6.495
render.lightOrthoHalf=8.805
render.lineWidthDefault=1.0
render.lineWidthHighlight=4.0
render.lineWidthPosition=5.0
render.lineWidthScaleRot=3.0
render.orthoHalfSize=6.0
render.shadowHeight=2048
render.shadowWidth=2048
render.sphereRadius=0.5
render.sphereSlices=20
render.sphereStacks=20
window.height=1080
window.swapInterval=1
window.title=3D Engine - Shadows & Slime Integrated
window.width=1920
